# travis continuous integration declaration for
# Emuflight

env:
  matrix:
    #- GOAL=test # make test # FIXME: fails
    - GOAL=targets-group-1 # make all (in parallel)
    - GOAL=targets-group-2
    - GOAL=targets-group-rest
  global:
    #- DEBUG=RELWITHDEBINFO # debug symbols
    - PATH="$HOME/.local/bin:$PATH" # "user" installs (pip and stuff)
    - CCACHE_SLOPPINESS="file_macro,time_macros,include_file_mtime,include_file_ctime,file_stat_matches"

sudo: false # be safe

git:
  depth: 5 # quick clone
  quiet: true # save on logfiles

addons:
  apt:
    packages:
      - build-essential
      - ccache
      - clang
      - g++
      - git
      - libblocksruntime-dev # required for linking on tests - http://mackyle.github.io/blocksruntime/
      - libc6-i386
      - llvm
      - time

cache:
  ccache: true
  pip: true
  directories:
  - downloads
  - tools

dist: bionic # ubuntu
language: cpp
compiler: clang

before_install:
  - pip install --user --upgrade j2cli
install:
  - make arm_sdk_install # toolchain

before_script:
  - clang --version
  - clang++ --version
  - gcc --version

script:
  - ./.travis.sh # main
  - ccache --show-stats

deploy:
  provider: bintray
  file: bintray-conf.json
  user: "$BINTRAY_USER"
  key: "$BINTRAY_API_KEY"
  skip_cleanup: true # do not delete what has just been built
  on:
    all_branches: true
    #branch: Main # just this specific branch

after_deploy:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
